### ISSUE TITLE
UNL 1.0.0-6 qemu issue

### ISSUE THREAD

**Issue by gcasella** [dainok/unetlab#117]
Hi,

I'm experiencing this with IOSv, XRV & Linux images (linux-tinycore, tells me no bootable devices exist) images in UNL.

I have the appropriate hda.qcow2 files in the respected directories on the UNL server.

Once I add my nodes to the topology and click "start node" it doesn't do anything.

The contents of /opt/unetlab/data/Logs/unl_wrapper.txt show that it is trying to start the node;

`/opt/unetlab/wrappers/qemu_wrapper -T 1 -D 1 -t "vIOS" -F /opt/qemu/bin/qemu-system-i386 -d 0 -- -device e1000,netdev=net0,mac=50:01:00:01:00:00 -netdev tap,id=net0,ifname=vunl1_1_0,script=no -device e1000,netdev=net1,mac=50:01:00:01:00:01 -netdev tap,id=net1,ifname=vunl1_1_1,script=no -device e1000,netdev=net2,mac=50:01:00:01:00:02 -netdev tap,id=net2,ifname=vunl1_1_2,script=no -device e1000,netdev=net3,mac=50:01:00:01:00:03 -netdev tap,id=net3,ifname=vunl1_1_3,script=no -smp 1 -m 1024 -name vIOS -uuid abef4191-4f11-444c-a67a-1943da7674a2 -hda hda.qcow2 -machine type=pc-1.0,accel=kvm -serial mon:stdio -nographic -nodefconfig -nodefaults -rtc base=utc > /opt/unetlab/tmp/1/07ccc028-815e-489b-93bc-1fa80b093d44/1/wrapper.txt 2>&1 &`

However it never truly starts the Node. I took that output above and did a copy and paste in the command line for UNL and then the Web GUI updated the topology showing it's now running -- once that happens I can log in and configure the device.

I can provide screenshots if required.

**Comment by 3XTron** [comment]
Since public release version UNL 1.0.0-6,  lot of bugs have been fixed in repo from GitHub, i recommend you to try the last UNL from GitHub.
Instruction (from root) ->
# apt-get update && apt-get upgrade -y && apt-get install genisoimage zip git -y && cd /usr/src  &&  git clone https://github.com/dainok/unetlab.git && /usr/src/unetlab/scripts/syncunl && /opt/unetlab/wrappers/unl_wrapper -a fixpermissions


Then try again, for more details -> [Youtube Video](https://www.youtube.com/watch?v=qu2Kz4L1m-4)

**Comment by 3XTron** [comment]
Try `/opt/unetlab/wrappers/unl_wrapper -a fixpermissions`
use tutorial http://www.unetlab.com/2014/11/adding-cisco-vios-images-from-all-in-one-virtual-machine/
check Youtube video https://www.youtube.com/watch?v=qu2Kz4L1m-4

**Comment by gcasella** [comment]
Things seem to be a little better this time around when using the most up to date version from the git repository.

My nodes are starting as expected, including IOSv. 
Note i don't use the image from the All In One virtual machine, i use official images from Cisco VIRL. 

Everything seems to be okay, as for my Linux qcow2 files, it appears the ones i have don't like to have their hard drives recognized. 

Thanks for the quick response!

**Comment by 3XTron** [comment]
Welcome and please close the issue.
