### ISSUE TITLE
UNL 1.0.0-7.004-git VirtualPC Support (VPCS)

### ISSUE THREAD

**Issue by gcasella** [dainok/unetlab#120]
Hi,

So while playing around with UNL a bit more, i noticed while adding a device there was the ability to add a VirtualPC (VPCS).

I downloaded VPCS 0.8 and placed it inside of /opt/vpcsu/bin/vpcs, fixed permissions and made it executable. 

checking the /opt/unetlab/data/Logs/unl_wrapper.txt file it shows;
`Apr 07 18:07:12 INFO: starting /opt/vpcsu/bin/vpcs -m 4 -N VPC4 -i 1 -p 32900  -e -d vunl1_4_0 > /opt/unetlab/tmp/1/5a462e27-634b-4d00-ad5e-4e4bf18079eb/4/wrapper.txt 2>&1 &`

Not starting of course, it seems the option `-N` is not liked by VPCS.

My `/opt/unetlab/tmp/1/5a462e27-634b-4d00-ad5e-4e4bf18079eb/4/wrapper.txt` file shows the following output;

`/opt/vpcsu/bin/vpcs: invalid option -- 'N'`

Please Advise.

Note: I do know that I could just simply use a Linux LiveCD, but I do like the speed and quick, and low memory from VPCS. If this will not be supported in upcoming releases than I look into TinyCore linux or MicroCore linux live images/qemu images. 

Thanks in advance.

**Comment by 3XTron** [comment]
Instruction will be provided after next release, check new instruction http://www.unetlab.com/documentation/index.html   or  Youtube https://www.youtube.com/c/UnifiedNetworkingLab

**Comment by gcasella** [comment]
Alright, i will wait for the next release and for any new instructions when the release is public.

**Comment by 3XTron** [comment]
Welcome and please close the issue.

**Comment by fallenfuzz** [comment]
Patience.
With next release lots of interesting stuff coming :)
