### ISSUE TITLE
Status tab error

### ISSUE THREAD

**Issue by zero13th** [dainok/unetlab#125]
reproducible: click status tab

SLIM APPLICATION ERROR
The application could not run because of the following error:

DETAILS
Type: ErrorException
Code: 2
Message: Division by zero
File: /opt/unetlab/html/includes/api_status.php
Line: 112

TRACE
#0 /opt/unetlab/html/includes/api_status.php(112): Slim\Slim::handleErrors(2, 'Division by zer...', '/opt/unetlab/ht...', 112, Array)
#1 /opt/unetlab/html/api.php(201): apiGetSwapUsage()
#2 [internal function]: {closure}()
#3 /opt/unetlab/html/includes/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /opt/unetlab/html/includes/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /opt/unetlab/html/includes/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /opt/unetlab/html/includes/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /opt/unetlab/html/includes/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /opt/unetlab/html/includes/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /opt/unetlab/html/api.php(1168): Slim\Slim->run()
#10 {main}

**Comment by fallenfuzz** [comment]
Try
apt-get install libaio1 libaio-dev

**Comment by zero13th** [comment]
root@unetlab:~# apt-get install libaio1 libaio-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libaio-dev is already the newest version.
libaio1 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@unetlab:~#

install packages and reboot = still error

**Comment by fallenfuzz** [comment]
refresh browser and clean cache

**Comment by zero13th** [comment]
tested using firefox and chrome, both new private session = still error

#0 /opt/unetlab/html/includes/api_status.php(112): Slim\Slim::handleErrors(2, 'Division by zer...', '/opt/unetlab/ht...', 112, Array)
#1 /opt/unetlab/html/api.php(201): apiGetSwapUsage()
#2 [internal function]: {closure}()
#3 /opt/unetlab/html/includes/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /opt/unetlab/html/includes/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /opt/unetlab/html/includes/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /opt/unetlab/html/includes/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /opt/unetlab/html/includes/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /opt/unetlab/html/includes/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#9 /opt/unetlab/html/api.php(1168): Slim\Slim->run()
#10 {main}

**Comment by fallenfuzz** [comment]
Try reinstalling.. should be fine

**Comment by PriyankaChopra** [comment]
I am getting the same error. Re installation doesn't help either..
