### ISSUE TITLE
Lab does not exist (60000)

### ISSUE THREAD

**Issue by zero13th** [dainok/unetlab#147]
using unetlab-1.0.0-8

1 create new username (user-a) with role editor
2 login using username 'user-a' and create iol lab "/test-lab/test-1.unl"
3 logout

4 login using username 'admin'
5 rename "/test-lab/test-1.unl" with /rename-lab/test-2.unl"
6 logout

7 login again using username 'user-a'
8 blank screen with error notification "Lab does not exist (60000)"
9 'user-a' cannot do anything (there was no menu / no logout button)

**Comment by fallenfuzz** [comment]
fixed in the next release.
For now fix from cli by creating lab and exiting it properly
