### ISSUE TITLE
vsrxng template using incorrect NIC driver causing L2 features to fail

### ISSUE THREAD

**Issue by igorzejdlyk** [dainok/unetlab#182]
/opt/unetlab/html/templates/vsrxng.php

needs changin the default ethernet NIC driver from e1000 to virtio-net as the L2 functions dont work properly with the default driver.

the line missing is:

`$p['qemu_nic'] = 'virtio-net-pci';`

**Comment by fallenfuzz** [comment]
Make a deeper tests to make sure that everything else works properly with that change

**Comment by igorzejdlyk** [comment]
After some research it seems that for vsrx the virtio is one of two supported NIC types on KVM types (the other being SR-IOV)  see: http://www.juniper.net/techpubs/en_US/vsrx15.1x49/topics/reference/general/security-vsrx-system-requirement-with-kvm.html
Anyway I am running some l2 and l3 tests now and all seems fine so far.
