### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by idarlund** [dainok/unetlab#183]
Is this project dead? Or is eve-ng (https://gitlab.com/eve-ng-dev/eve-ng-public) just a fork?

**Comment by fallenfuzz** [comment]
Hi,

Project is not dead.
EVE is the next major version, not just fork.

We do not code UNL anymore, but working hard on EVE.

If you want to contribute, contribute for EVE

**Comment by idarlund** [comment]
So THIS project is dead, but you have moved over to https://gitlab.com/eve-ng-dev/eve-ng-public ? :)

**Comment by fallenfuzz** [comment]
Yep, probably :)

**Comment by mshalmanov** [comment]
> So THIS project is dead, but you have moved over to https://gitlab.com/eve-ng-dev/eve-ng-public ? :)

Hello. Link isn't work (broken). Where i can take work link ?
