### ISSUE TITLE
Can't start xrv-k9-5.3.1

### ISSUE THREAD

**Issue by romale** [dainok/unetlab#30]
Hi,
I've installed UNL 0.9.0-76.
When i try to start XRv, it's say "Node(s) started, please wait", but really it's not started.

/opt/unetlab/data/Logs/unl_wrapper.txt has lines:

INFO: CWD is /opt/unetlab/tmp/0/f6b3862c-476f-4f1b-b17b-37a38a7d0bfb/1
INFO: starting /opt/unetlab/wrappers/qemu_wrapper -T 0 -D 1 -t "xrv" -F /opt/qemu/bin/qemu-system-i386 -d 0 -- -device e1000,netdev=net0,mac=50:00:00:01:00:00 -netdev tap,id=net0,ifname=vunl0_1_0,script=no -devi
ce e1000,netdev=net1,mac=50:00:00:01:00:01 -netdev tap,id=net1,ifname=vunl0_1_1,script=no -device e1000,netdev=net2,mac=50:00:00:01:00:02 -netdev tap,id=net2,ifname=vunl0_1_2,script=no -device e1000,netdev=net3,
mac=50:00:00:01:00:03 -netdev tap,id=net3,ifname=vunl0_1_3,script=no -smp 1 -m 3072 -name xrv -uuid 61373116-deac-4196-9989-1e5151004204 -hda hda.qcow2 -machine type=pc-1.0,accel=kvm -serial mon:stdio -nographic
 -nodefconfig -nodefaults -rtc base=utc -no-shutdown -boot order=c > /opt/unetlab/tmp/0/f6b3862c-476f-4f1b-b17b-37a38a7d0bfb/1/wrapper.txt 2>&1 &

File /opt/unetlab/tmp/0/f6b3862c-476f-4f1b-b17b-37a38a7d0bfb/1/wrapper.txt has line:

0:1 ERR: error while reading data from the subprocess, killing it.

Could you help?

**Comment by dainok** [comment]
This is not a support forum. If you find a bug, provide a patch.
