### ISSUE TITLE
UNL doesnt check if port is in use

### ISSUE THREAD

**Issue by chppppp** [dainok/unetlab#49]
steps to replicate the issue:
1. Create new lab, add device, turn on device. UNL assigns this device port 32769 for remote access via telnet. Is accessible from the topology as telnet://ipaddress:32769
2. Create a 2nd new lab, add device, turn on, UNL also gives this device port 32769. 

UNL Does no sanity checking for sockets in use before assigning ports to devices which ends up only being able to run 1 lab at time. 

I will poke through the code myself but I thought this was worth a ticket. 

UNetLab version: 0.9.0-96
QEMU version: 2.4.0

Thank you

**Comment by chppppp** [comment]
here is the problem:

```
ts_port = 32768 + 128 * tenant_id + device_id
```

When someone adds devices to a new lab, it always gives the first device the ID of 1. It would probably be better to write this so that when a user adds a device to a lab, the lab# is prepended to the device ID. That way every device ID in each lab isnt sharing the same integer and you can still use that little formula.

**Comment by fallenfuzz** [comment]
Hi,

That is by design.
One user can run only one lab at any given time.
If multiple labs needed to run - create multiple users, that will allow to run multiple labs or same lab simultaneously

**Comment by chppppp** [comment]
I forked the repo, going to see if I can change this to behave like I want. 

Thank you for the fast response. Great product.
