### ISSUE TITLE
LACP and LLDP Support on Bridge Interfaces

### ISSUE THREAD

**Issue by armartirosyan** [dainok/unetlab#77]
I am running 2 Arista vEOS and simple LACP configuration fails. Packet capture shows active LACP (to that matter LLDP) broadcast on the link but neighboring device does not receive them. Unetlab is running on ubuntu 14.04LTS server version with `4.2.0-30-generic` kernel version.

**Comment by eczema** [comment]
you need to patch the kernel.... 
https://github.com/dainok/unetlab/blob/master/patch/linux-lts-utopic-3.16.0.patch

**Comment by zengxinhui** [comment]
@armartirosyan stick with unetlab stock kernel not ubuntu kernel
@eczema i believe the stock kernal is patched

linux-headers-3.16.7-ckt8-unetlab
linux-image-3.16.7-ckt8-unetlab

**Comment by fallenfuzz** [comment]
@zengxinhui correct
