### ISSUE TITLE
My last commit breaks xrv qemu (pull request #78 )

### ISSUE THREAD

**Issue by eczema** [dainok/unetlab#82]
Indeed, the IOS-XRV kernel doesn't support the virtio-blk-pci.
Only ide-hd is supported....

A way  to fix it:
Rollback and use a new mechanism to  call virtio:
into addon/qemu, using virtio-hdx.qcow2 could call a new way to construct flags 

I'll work on it with your advices and your preferences....

**Comment by eczema** [comment]
Second possibility is to add a new option in template to choose the IDE driver.... As you like.....

**Comment by dainok** [comment]
I added a virtide option. Check if it works better.

**Comment by fallenfuzz** [comment]
xr works fine
