### ISSUE TITLE
Copying a Lab with Qemu VM's does not copy the configs 

### ISSUE THREAD

**Issue by alsenior** [dainok/unetlab#83]
When copying a Lab with a Qemu VM the VM is not started with HDA.qcow in the tmp folder. This causes all Qemu VM to start in a blank state. 

Steps to reproduce: 

1) Create a Qemu VM node and make a change and save the change
2)Shutdown VM
3) Copy Lab 
4) Start VM 

Affects: 
Alcatel vSR
Linux 
Juniper VSRX
(Other Qemu node's probably)

Workaround: 

None Known

**Comment by alsenior** [comment]
Logs from attached
[unl_wrapper.txt](https://github.com/dainok/unetlab/files/172560/unl_wrapper.txt)

**Comment by alsenior** [comment]
Logs Attached 
[unl_wrapper.txt](https://github.com/dainok/unetlab/files/172561/unl_wrapper.txt)

**Comment by fallenfuzz** [comment]
can you show via teamviewer?

**Comment by dainok** [comment]
You're not using the UNetLab kernel.

**Comment by alsenior** [comment]
Issue Still Present when using Unetlab kernel

alsenior@labserver 8:05 ~ uname -a  
Linux labserver 3.16.7-ckt8-unetlab #1 SMP Thu Apr 23 17:44:20 IDT 2015 x86_64 x86_64 x86_64 GNU/Linux
